# Generated by Django 4.0.1 on 2022-03-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRecruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=30, verbose_name='曲名')),
                ('parts', models.TextField(max_length=50, verbose_name='募集パート')),
                ('comment', models.TextField(max_length=1000, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
