# Generated by Django 4.0.1 on 2022-03-14 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_postapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='postapplication',
            name='a_target',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mainapp.postrecruit', verbose_name='対象の募集'),
            preserve_default=False,
        ),
    ]
