# Generated by Django 4.0.1 on 2022-04-02 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_high_low_middle_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(max_length=300, verbose_name='自己紹介')),
                ('p_part', models.TextField(max_length=200, verbose_name='主な担当')),
                ('freetime', models.TextField(max_length=300, verbose_name='空いている時間')),
                ('p_created_at', models.DateTimeField(auto_now_add=True)),
                ('p_update_at', models.DateTimeField(auto_now=True)),
                ('p_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='サークルネーム')),
            ],
        ),
    ]
