# Generated by Django 4.0.1 on 2022-04-02 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_postprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprofile',
            name='high',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='mainapp.high'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postprofile',
            name='low',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='mainapp.low'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postprofile',
            name='middle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.middle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postprofile',
            name='sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.sex'),
            preserve_default=False,
        ),
    ]
