# Generated by Django 4.0.1 on 2022-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='top_info',
            field=models.CharField(default=1, max_length=150, verbose_name='TOPページおしらせ'),
            preserve_default=False,
        ),
    ]
